- name: Install `n` to manage node versions
  shell: brew install n
  tags:
    - node
- name: Set up `n`
  shell: |
    mkdir -p /usr/local/n
    chown -R {{ ansible_facts["user_id"] }} /usr/local/n
    mkdir -p /usr/local/bin /usr/local/lib /usr/local/include /usr/local/share
    chown -R {{ ansible_facts["user_id"] }} /usr/local/bin /usr/local/lib /usr/local/include /usr/local/share
  become: yes
  tags:
    - node
- name: Install latest Node.js LTS
  shell: n lts
  become: yes
  tags:
    - node
