- name: Install Yarn
  shell: corepack enable
  tags:
    - npm
- name: Install eslint
  npm:
    name: eslint
    global: yes
  tags:
    - npm
- name: Install Typescript server
  npm:
    name: typescript-language-server
    global: yes
  tags:
    - npm
- name: Install Typescript
  npm:
    name: typescript
    global: yes
  tags:
    - npm
- name: Install TS-Node
  npm:
    name: ts-node
    global: yes
  tags:
    - npm
- name: Install Gemini CLI
  npm:
    name: "@google/gemini-cli"
    global: yes
  tags:
    - npm
- name: Install Mermaid CLI
  npm:
    name: "@mermaid-js/mermaid-cli"
    global: yes
  tags:
    - npm
- name: Install markdownlint-cli
  npm:
    name: markdownlint-cli
    global: yes
  tags:
    - npm
- name: Install Pyright
  npm:
    name: pyright
    global: yes
  tags:
    - npm
- name: Install Yeoman
  npm:
    name: yo
    global: yes
  tags:
    - npm
- name: Install Office Add-in generator
  npm:
    name: generator-office
    global: yes
  tags:
    - npm
