---
downloads: ~/.ansible-downloads/

configure_mac: true
configure_zsh: true
configure_homebrew_taps: true
configure_homebrew_packages: true
configure_homebrew_casks: true
configure_node: true
configure_npm: true
configure_dev_tools: true
configure_dotfiles: true
configure_pipx: true
configure_go: true
configure_vscode: true
