import = [
    "~/.config/alacritty/themes/themes/dracula.toml"
]

[window]
dimensions = { columns = 80, lines = 40 }
decorations = "Full"
startup_mode = "Maximized"

[scrolling]
history = 100000

[font]
normal = { family = "MesloLGS NF", style = "Regular" }
size = 18

[mouse]
hide_when_typing = true

